platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'BIASystemKit',
    git: 'https://github.com/StefaniOSApps/BIASystemKit.git',
    branch: 'swift-5.3-beta'

  # Pods for Example

end
