update_fastlane
default_platform(:ios)

platform :ios do
  desc "Run Tests"
  lane :laneTests do
    run_tests(
      scheme: "BIASystemKit-Package",
      devices: ['iPhone 8 Plus'],
      clean: true
    )
  end
end
