name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.5,name=iPhone 8 Plus']
        xcode: ['/Applications/Xcode_11.4.app/Contents/Developer']

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Bundle Install
        run: bundle install
      - name: Bundle Update
        run: bundle update
      - name: Build and test
        run: bundle exec fastlane ios laneTests

